name       : aha
version    : 0.5.1
release    : 1
source     :
    - https://github.com/theZiz/aha/archive/refs/tags/0.5.1.tar.gz : 6aea13487f6b5c3e453a447a67345f8095282f5acd97344466816b05ebd0b3b1
homepage   : https://github.com/theZiz/aha
license    : LGPL-2.1-or-later
component  : system.utils
summary    : Ansi HTML Adapter
description: |
    Converts ANSI escape sequences of a unix terminal to HTML code.
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
